# Generated by Django 4.2.2 on 2023-06-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetup', '0003_remove_event_members_event_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='python_meetup.user', verbose_name='кто задал'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('speaker', 'speaker'), ('customer', 'customer'), ('unregistered_customer', 'unregistered_customer')], max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='unregistered_customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='python_meetup.role', verbose_name='роль'),
        ),
    ]
