# Generated by Django 4.2.2 on 2023-06-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetup', '0004_alter_question_user_alter_role_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['time_start']},
        ),
    ]
